spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simplyinvite
    username: postgres
    password: jonas1385
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  security:
    jwt:
      secret: ${JWT_SECRET:simplyinvite-secret-key-2024-development-environment}
      expiration: 86400000 # 24 horas em milissegundos

server:
  port: 8080
  # servlet:
  # context-path: /api

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

logging:
  level:
    org.springframework.security: DEBUG
    com.simplyinvite: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
